### PR TITLE
Update Russian translation and fix (not complete TOCyric.baf)

### PR DESCRIPTION
**Pull request by abalabokhin**
I updated Russian translation.

p_zombe also found that the line (@9) that appear on Cyric's head when he got godsbane is from tocyric.tra file not from  SandrahTot.tra (cause baf and tra files have the same names). The fix for it (in this pull request) is to add the corresponding line into tocyric.tra file. Another possible fix I can think of is to rename baf or tra file. Specifying "USING SandrahTot.tra" didn't work for him.

Also he said that Cyric doesn't equip the godsbane, that is why he removed "EquipItem("RTGodsb")" line from TOCyric.baf. Unfortunately, p_zombie doesn't know what to do to have Cyric equipped the item. But it is a minor problem.

### CODE REVIEW

**Comment by abalabokhin** [comment]
Corrected the desription, after better understanding the problem.

**Comment by RoxanneSHS** [comment]
I can reproduce the string display error but I cannot find any reason for the issue reported with the sword. Cyric (in my installation) is an Assassin (as he should be) and he can use godsbane which is classified as a short sword. He ca use it as main weapon or in the offhand slot. ToCyric.cre and RTGodsb.itm. The item is found on the halfling Sneakabout after the battle with him and there is no reason why there should be two items. Only explanation is some other mod interfering here.

**Comment by abalabokhin** [comment]
We don't have the problem with him not being able to use the sword (I misunderstood it), but EquipItem("RTGodsb") doesn't equip the item. However, you can give hime the sword manually after it, so it is not a big deal.

Overall, everything works (almost), no problem,  thank you.

**Comment by RoxanneSHS** [comment]
I see...it is true that the action EquipItem does not always work in the current game version. I have seen some occasions myself in EET. It is not related to a specific item or script but seems to happen randomly wherever used. It is one of those difficult scripting events that behave differently after the last official game update. But it should only ever be an inconvenience and not a big issue.

**Pull request merged**
